services:
  ecole_42:
    hostname: 42 São Paulo
    build: 
      context: .
    volumes:
      - ../volume:/volume
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0
