services:
  ecole_42:
    hostname: 42SP
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../volume:/volume
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0
